driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: centos-6.9
  - name: centos-7.3
  - name: debian-7.11
  - name: oracle-7.3
  - name: debian-8.7
  - name: fedora-25
  - name: opensuse-leap-42.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: amazon-linux
    driver_config:
      box: mvbcoding/awslinux
  
suites:
  - name: create
    run_list:
      - recipe[test::create]
  - name: create_thin
    excludes:
    - debian-7.11
    run_list:
      - recipe[test::create_thin]
  - name: resize
    run_list:
      - recipe[test::create]
      - recipe[test::resize]
  - name: resize_thin
    excludes:
    - debian-7.11
    run_list:
      - recipe[test::create_thin]
      - recipe[test::resize_thin]
